services:
  nginx:
    image: nginx:alpine
    container_name: ai_job_agent_nginx_container
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/certbot/www:/var/www/certbot:ro
    depends_on:
      - frontend
    networks:
      - default

